config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :dashes

root 'dashes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dash.rb
class Dash < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashes_controller.rb
class DashesController < ApplicationController
  before_action :set_dash, only: %i[ show edit update destroy ]

  # GET /dashes or /dashes.json
  def index
    @dashes = Dash.all
  end

  # GET /dashes/1 or /dashes/1.json
  def show
  end

  # GET /dashes/new
  def new
    @dash = Dash.new
  end

  # GET /dashes/1/edit
  def edit
  end

  # POST /dashes or /dashes.json
  def create
    @dash = Dash.new(dash_params)

    respond_to do |format|
      if @dash.save
        format.html { redirect_to @dash, notice: "Dash was successfully created." }
        format.json { render :show, status: :created, location: @dash }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashes/1 or /dashes/1.json
  def update
    respond_to do |format|
      if @dash.update(dash_params)
        format.html { redirect_to @dash, notice: "Dash was successfully updated." }
        format.json { render :show, status: :ok, location: @dash }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashes/1 or /dashes/1.json
  def destroy
    @dash.destroy
    respond_to do |format|
      format.html { redirect_to dashes_url, notice: "Dash was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dash
      @dash = Dash.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dash_params
      params.require(:dash).permit(:no, :desc)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]

  # GET /homes or /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1 or /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.require(:home).permit(:descr)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashes_helper.rb
module DashesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/dashes/_form.html.erb
<%= form_with(model: dash, local: true) do |form| %>
  <% if dash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dash.errors.count, "error") %> prohibited this dash from being saved:</h2>

      <ul>
        <% dash.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :no %>
    <%= form.text_area :no %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dashes/edit.html.erb
<h1>Editing Dash</h1>

<%= render 'form', dash: @dash %>

<%= link_to 'Show', @dash %> |
<%= link_to 'Back', dashes_path %>

app/views/dashes/new.html.erb
<h1>New Dash</h1>

<%= render 'form', dash: @dash %>

<%= link_to 'Back', dashes_path %>

app/views/dashes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No:</strong>
  <%= @dash.no %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @dash.desc %>
</p>

<%= link_to 'Edit', edit_dash_path(@dash) %> |
<%= link_to 'Back', dashes_path %>

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
        <% home.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descr %>
    <%= form.text_area :descr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descr:</strong>
  <%= @home.descr %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pacfapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>


<meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="description" content="The Kenya Vaccine  registry "><meta name="keywords" content="Kenya, Covid-19, vaccine Registry"><meta name="author" content="Ministry of health"><meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,minimal-ui"><title>Covid-19 Registry</title><link href="/js/chunk-2d216214.a631c492.js" rel="prefetch"><link href="/js/chunk-6eb196aa.0a2e21da.js" rel="prefetch"><link href="/css/app.108abc8d.css" rel="preload" as="style"><link href="/css/chunk-vendors.d4532c15.css" rel="preload" as="style"><link href="/js/app.fc0da093.js" rel="preload" as="script"><link href="/js/chunk-vendors.f3196445.js" rel="preload" as="script"><link href="/css/chunk-vendors.d4532c15.css" rel="stylesheet"><link href="/css/app.108abc8d.css" rel="stylesheet">


  </head>



  <body>

<class="vertical-layout"><div id="app"></div><script src="/js/chunk-vendors.f3196445.js"></script><script src="/js/app.fc0da093.js"></script>
    <%= yield %>
  </body>
</html>